Added feature request template
anwilli5/coin-collection-android-US pull request #88
Opened 2022-10-02 19:13 UTC by ManasviGoyal

Fixes #86 

![image](https://user-images.githubusercontent.com/55101825/193471953-b988cf41-c044-4086-a6a5-4afc21403b7e.png)

2022-10-02 19:13 UTC, ManasviGoyal commented
Please check @sw23

2022-10-02 23:47 UTC, sw23 requested changes

2022-10-02 23:47 UTC, sw23 commented on .github/ISSUE_TEMPLATE/feature_request_template.yaml
> +      label: "💭 Description"
```suggestion
      label: "💭 Feature Description"
```

2022-10-02 23:47 UTC, sw23 commented on .github/ISSUE_TEMPLATE/feature_request_template.yaml
> +      description: "Add any other context about the problem here. Link any related issues here."
I think we can keep it simple and just have a single text box
```suggestion
```

2022-10-03 00:12 UTC, ManasviGoyal commented
Added the requested changes. Please check @sw23. Thanks.

2022-10-03 00:59 UTC, sw23 approved these changes

2022-10-03 01:44 UTC, merged